// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_listener_by_uuid.sql

package db

import (
	"context"
)

const getListenerByUUID = `-- name: GetListenerByUUID :one
SELECT id, uuid, user_id, created_at FROM listeners WHERE uuid = $1
`

func (q *Queries) GetListenerByUUID(ctx context.Context, uuid string) (Listener, error) {
	row := q.db.QueryRowContext(ctx, getListenerByUUID, uuid)
	var i Listener
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
