// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listeners.sql

package db

import (
	"context"
)

const createListener = `-- name: CreateListener :one
INSERT INTO listeners (uuid, user_id) VALUES ($1, $2)
RETURNING id, uuid, user_id, created_at
`

type CreateListenerParams struct {
	Uuid   string
	UserID int32
}

func (q *Queries) CreateListener(ctx context.Context, arg CreateListenerParams) (Listener, error) {
	row := q.db.QueryRowContext(ctx, createListener, arg.Uuid, arg.UserID)
	var i Listener
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getListenersByUser = `-- name: GetListenersByUser :many
SELECT id, uuid, user_id, created_at FROM listeners WHERE user_id = $1
`

func (q *Queries) GetListenersByUser(ctx context.Context, userID int32) ([]Listener, error) {
	rows, err := q.db.QueryContext(ctx, getListenersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listener
	for rows.Next() {
		var i Listener
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
