// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listeners.sql

package db

import (
	"context"
	"database/sql"
)

const createListener = `-- name: CreateListener :one
INSERT INTO listeners (uuid, user_id, name) VALUES ($1, $2, $3)
RETURNING id, uuid, user_id, created_at, name
`

type CreateListenerParams struct {
	Uuid   string
	UserID int32
	Name   sql.NullString
}

func (q *Queries) CreateListener(ctx context.Context, arg CreateListenerParams) (Listener, error) {
	row := q.db.QueryRowContext(ctx, createListener, arg.Uuid, arg.UserID, arg.Name)
	var i Listener
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const deleteListener = `-- name: DeleteListener :exec
DELETE FROM listeners WHERE uuid = $1
`

func (q *Queries) DeleteListener(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteListener, uuid)
	return err
}

const getListenersByUser = `-- name: GetListenersByUser :many
SELECT id, uuid, user_id, created_at, name FROM listeners WHERE user_id = $1
`

func (q *Queries) GetListenersByUser(ctx context.Context, userID int32) ([]Listener, error) {
	rows, err := q.db.QueryContext(ctx, getListenersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listener
	for rows.Next() {
		var i Listener
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListenerName = `-- name: UpdateListenerName :exec
UPDATE listeners SET name = $2 WHERE uuid = $1
`

type UpdateListenerNameParams struct {
	Uuid string
	Name sql.NullString
}

func (q *Queries) UpdateListenerName(ctx context.Context, arg UpdateListenerNameParams) error {
	_, err := q.db.ExecContext(ctx, updateListenerName, arg.Uuid, arg.Name)
	return err
}
