// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"
)

type Listener struct {
	ID        int32
	Uuid      string
	UserID    int32
	CreatedAt time.Time
}

type Request struct {
	ID         int32
	ListenerID int32
	Timestamp  time.Time
	Headers    json.RawMessage
	Body       string
}

type Session struct {
	ID        int32
	SessionID string
	UserID    int32
	CreatedAt time.Time
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
}
