// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"
	"encoding/json"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (listener_id, headers, body) VALUES ($1, $2, $3)
RETURNING id, listener_id, timestamp, headers, body
`

type CreateRequestParams struct {
	ListenerID int32
	Headers    json.RawMessage
	Body       string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest, arg.ListenerID, arg.Headers, arg.Body)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.Timestamp,
		&i.Headers,
		&i.Body,
	)
	return i, err
}

const getRequestsByListener = `-- name: GetRequestsByListener :many
SELECT id, listener_id, timestamp, headers, body FROM requests WHERE listener_id = $1 ORDER BY timestamp DESC
`

func (q *Queries) GetRequestsByListener(ctx context.Context, listenerID int32) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getRequestsByListener, listenerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ListenerID,
			&i.Timestamp,
			&i.Headers,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
