services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: webhooktester
      POSTGRES_PASSWORD: webhooktester
      POSTGRES_DB: webhooktester
    ports:
      - "55432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
volumes:
  db_data:

